// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for windows - '
      //         'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      // case TargetPlatform.linux:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for linux - '
      //         'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcPaDTfyXaJSDAkct8Mdp5gD_UHSAWbd0',
    appId: '1:644464345336:web:954445147e788662bdbb0d',
    messagingSenderId: '644464345336',
    projectId: 'alumniapp-7ab06',
    authDomain: 'alumniapp-7ab06.firebaseapp.com',
    storageBucket: 'alumniapp-7ab06.appspot.com',
    // measurementId: 'G-5758Z105K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcPaDTfyXaJSDAkct8Mdp5gD_UHSAWbd0',
    appId: '1:644464345336:web:954445147e788662bdbb0d',
    messagingSenderId: '644464345336',
    projectId: 'alumniapp-7ab06',
    storageBucket: 'alumniapp-7ab06.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyA763_ymiHh1bzlLksXyOuO1lC0FG640C0',
  //   appId: '1:281804722433:ios:8ac270df51a98678570b00',
  //   messagingSenderId: '281804722433',
  //   projectId: 'alumnihub-574d5',
  //   storageBucket: 'alumnihub-574d5.appspot.com',
  //   iosBundleId: 'com.example.alumnihub',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyA763_ymiHh1bzlLksXyOuO1lC0FG640C0',
  //   appId: '1:281804722433:ios:b0cdcdb37d84b26b570b00',
  //   messagingSenderId: '281804722433',
  //   projectId: 'alumnihub-574d5',
  //   storageBucket: 'alumnihub-574d5.appspot.com',
  //   iosBundleId: 'com.example.alumnihub.RunnerTests',
  // );
}
